src/Data/Entity/Groupable.php
<?php

namespace MdNetdesign\ContaoEntities\Data\Entity;

interface Groupable
{

  public function getGroup(): string;

}

src/Resources/views/default.html.twig
{% block header %}
  <th class="tl_folder_tlist">?</th>
{% endblock %}

{% block entry %}
  <td class="tl_file_list">?</td>
{% endblock %}

src/Resources/views/edit.html.twig
{% extends "@ContaoCore/Backend/be_page.html.twig" %}

{% block headline %}
  {{ (entity is null ? 'create_instance' : 'edit_instance')|trans({
    __type__: instanceTitle|trans,
    __id__: entity.id|default(null)
  }) }}
{% endblock %}

{% block error %}{% endblock %}

{% block main %}
  <div id="tl_buttons">
    {% block actions %}
      <a href="{{ path(baseRoute ~ '-list') }}" class="header_back" accesskey="b" title="{{ 'back'|trans }}" onclick="Backend.getScrollOffset()">{{ 'back'|trans }}</a>
    {% endblock %}
  </div>

  {% block form %}
    {% form_theme form contaoEntitiesFormTheme|default('@ContaoEntities/form-theme.html.twig') %}
    {{ form_start(form) }}

    {% block formBody %}
      <div class="tl_formbody_edit">

        {% for fieldset in fieldsets %}
          <fieldset id="pal_form" class="tl_box">
            <legend onclick="this.parentElement.classList.toggle('collapsed');">{{ fieldset|default('default_fieldset')|trans }}</legend>

            {% for children in form.children|filter(c => c.vars.row_attr['data-fieldset']|default(null) == fieldset) %}
              {{ form_row(children) }}
            {% endfor %}

            <div class="clr"></div>
          </fieldset>
        {% endfor %}

      </div>
    {% endblock %}

    {% block submitContainer %}
      <div class="tl_formbody_submit">
        <div class="tl_submit_container">
          {% block submit %}
            <button type="submit" name="save" id="save" class="tl_submit" accesskey="s">{{ 'save'|trans }}</button>
            <button type="submit" name="save" value="close" id="saveNclose" class="tl_submit" accesskey="c">{{ 'save_and_close'|trans }}</button>
          {% endblock %}
        </div>
      </div>
    {% endblock %}

    {{ form_end(form) }}
  {% endblock %}
{% endblock %}

src/Resources/views/list.html.twig
{% extends "@ContaoCore/Backend/be_page.html.twig" %}

{% block headline %}
  {{ title|trans }}
{% endblock %}

{% block error %}{% endblock %}

{% block main %}

  {% block filter %}
    {% set limitSubpanel %}
      <div class="tl_limit tl_subpanel">
        <strong>
          <label for="page">{{ 'do.limit'|trans }}</label>
        </strong>
        <select id="page" class="tl_select" onchange="location.href={{ path(baseRoute ~ '-list', {page: '0', edit: editMode})|json_encode }}.replace(/0$/i, this.value);">
          <option value="1">{{ 'datasets'|trans }}</option>
          {% for pageCandidate in 1..availablePages %}
            <option value="{{ pageCandidate }}"{% if page == pageCandidate %} selected{% endif %}>{{ (pageCandidate - 1) * entitiesPerPage + 1 }} - {{ min(totalEntityCount, (pageCandidate) * entitiesPerPage) }}</option>
          {% endfor %}
          <option value="0"{% if page == 0 %} selected{% endif %}>{{ 'all'|trans }}</option>
        </select>
      </div>
    {% endset %}
    {% if filterForm is not null %}
      {% if filterForm.children|keys|filter(k => k not in ['REQUEST_TOKEN', '_token']) is not empty %}
        {{ form_start(filterForm, {attr: {class: 'tl_form'}}) }}
        <div class="tl_formbody">
          {% set filters = filterForm.children|keys|filter(k => k not in ['REQUEST_TOKEN', '_token', 'search', 'orderBy', 'page']) %}
          {% if filters|length %}
            <div class="tl_panel cf">
              <div class="tl_filter tl_subpanel">
                <strong>{{ 'do.filter'|trans }}</strong>
                {% for filter in filters %}
                  {{ form_widget(filterForm[filter], {attr: {class: 'tl_select'}}) }}
                {% endfor %}
              </div>
            </div>
          {% endif %}
          <div class="tl_panel cf">
            <div class="tl_submit_panel tl_subpanel">
              <button id="filter" class="tl_img_submit filter_apply" title="{{ 'apply'|trans }}">{{ 'apply'|trans }}</button>
              <button name="filter-reset" id="filter_reset" value="reset" class="tl_img_submit filter_reset" title="{{ 'reset'|trans }}">{{ 'reset'|trans }}</button>
            </div>
            {% if totalEntityCount > 0 %}
              {{ limitSubpanel }}
            {% endif %}
            {% if 'search' in filterForm.children|keys %}
              <div class="tl_search tl_subpanel">
                <strong>
                  {{ form_label(filterForm.search) }}
                </strong>
                {{ form_widget(filterForm.search, {attr: {class: 'tl_text', style: 'width:68%;'}}) }}
              </div>
            {% endif %}
            {% if 'orderBy' in filterForm.children|keys %}
              <div class="tl_sorting tl_subpanel">
                <strong>
                  {{ form_label(filterForm.orderBy) }}
                </strong>
                {{ form_widget(filterForm.orderBy, {attr: {class: 'tl_select'}}) }}
              </div>
            {% endif %}
          </div>
        </div>
        {{ form_end(filterForm) }}
      {% endif %}
    {% elseif totalEntityCount > 0 %}
      <div class="tl_panel cf">
        {{ limitSubpanel }}
      </div>
    {% endif %}
  {% endblock %}

  {% set showSelectForm = (editMode == 'multiple' and selectForm is not null) %}

  {% block globalButtons %}
    {% if showSelectForm %}
      <div id="tl_buttons">
        <a href="{{ path(baseRoute ~ '-list') }}" class="header_back" accesskey="b" title="{{ 'back'|trans }}" onclick="Backend.getScrollOffset()">{{ 'back'|trans }}</a>
      </div>
    {% elseif canCreate or (canDeleteMultiple and totalEntityCount > 0) or block('actions', listTemplate) is defined %}
      <div id="tl_buttons">
        {% if canCreate %}
          <a href="{{ path(baseRoute ~ '-create') }}" class="header_new" accesskey="n" title="{{ 'new'|trans }}" onclick="Backend.getScrollOffset()">{{ 'new'|trans }}</a>
        {% endif %}
        {% if canDeleteMultiple and totalEntityCount > 0 %}
          <a href="{{ path(baseRoute ~ '-list', {edit: 'multiple'}) }}" class="header_edit_all" accesskey="e" title="{{ 'edit_multiple'|trans }}" onclick="Backend.getScrollOffset()">{{ 'edit_multiple'|trans }}</a>
        {% endif %}
        {% if block('actions', listTemplate) is defined %}
          {{ block('actions', listTemplate) }}
        {% endif %}
      </div>
    {% endif %}
  {% endblock %}

  {% if entities|length > 0 %}
    {% set actions = canEdit or canDelete or block('additionalEntryActions', listTemplate) is defined or showSelectForm %}
    {% if showSelectForm %}
      {{ form_start(selectForm) }}
    {% endif %}
    <div class="tl_listing_container list_view" id="tl_listing">
      {% if showSelectForm %}
        <div class="tl_select_trigger">
          <label for="tl_select_trigger" class="tl_select_label">{{ 'select_all'|trans }}</label>
          <input type="checkbox" id="tl_select_trigger" onclick="Backend.toggleCheckboxes(this)" class="tl_tree_checkbox">
        </div>
      {% endif %}
      {% set previousGroup = null %}
      <table class="tl_listing showColumns">
        <tbody>
        <tr>
          {{ block('header', listTemplate) }}
          {% if actions %}
            <th class="tl_folder_tlist tl_right_nowrap"></th>
          {% endif %}
        </tr>
        {% for entity in entities %}
          {% if groupable and previousGroup != entity.group %}
            {% set previousGroup = entity.group %}
            <tr>
              {{ block('group', listTemplate) }}
              {% if actions %}
                <th class="tl_folder_tlist tl_right_nowrap"></th>
              {% endif %}
            </tr>
          {% endif %}
          <tr class="even click2edit toggle_select hover-row">
            {{ block('entry', listTemplate) }}
            {% if actions %}
              {% if showSelectForm %}
                <td class="tl_file_list tl_right_nowrap">
                  {{ form_widget(selectForm['entity' ~ entity.id]) }}
                </td>
              {% else %}
                <td class="tl_file_list tl_right_nowrap">
                  {% block additionalActions %}
                    {% if block('additionalEntryActions', listTemplate) is defined %}
                      {{ block('additionalEntryActions', listTemplate) }}
                    {% endif %}
                  {% endblock %}
                  {% block actions %}
                    {% if canEdit and isEntityEditable.call(entityController, entity) %}
                      <a href="{{ path(baseRoute ~ '-edit', {id: entity.id}) }}" title="{{ 'edit_element'|trans({__id__: entity.id}) }}" class="edit"><img src="{{ asset('system/themes/flexible/icons/edit.svg') }}" width="16" height="16" alt="{{ 'edit_element'|trans({__id__: entity.id}) }}"></a>
                    {% endif %}
                    {% if canDuplicate and isEntityEditable.call(entityController, entity) %}
                      <a href="{{ path(baseRoute ~ '-duplicate', {id: entity.id}) }}" title="{{ 'duplicate_element'|trans({__id__: entity.id}) }}" class="copy"><img src="{{ asset('system/themes/flexible/icons/copy.svg') }}" width="16" height="16" alt="{{ 'duplicate_element'|trans({__id__: entity.id}) }}"></a>
                    {% endif %}
                    {% if canDelete and isEntityDeletable.call(entityController, entity) %}
                      <a href="{{ path(baseRoute ~ '-delete', {id: entity.id}) }}" title="{{ 'delete_element'|trans({__id__: entity.id}) }}" class="delete" onclick="return confirm('{{ 'delete_confirm'|trans({__id__: entity.id}) }}')"><img src="{{ asset('system/themes/flexible/icons/delete.svg') }}" width="16" height="16" alt="{{ 'delete_element'|trans({__id__: entity.id}) }}"></a>
                    {% endif %}
                  {% endblock %}
                </td>
              {% endif %}
            {% endif %}
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
    {% if showSelectForm %}
      {% block submitContainer %}
        <div class="tl_formbody_submit" style="text-align:right;">
          <div class="tl_submit_container">
            {% block submit %}
              <button type="submit" name="action" value="delete" class="tl_submit" accesskey="d" onclick="return confirm('{{ 'delete_multiple_confirm'|trans }}')">{{ 'delete'|trans }}</button>
            {% endblock %}
          </div>
        </div>
      {% endblock %}

      {{ form_end(selectForm) }}
    {% endif %}
  {% else %}
    <p class="tl_empty">{{ 'no_entries_found'|trans }}</p>
  {% endif %}
{% endblock %}